# Configuration du serveur
server:
  port: 9000
  http2:
    enabled: true
  compression:
    enabled: true
  servlet:
    context-path: '/api/v1'

# Configuration de la source de données
spring:
  datasource:
    url: jdbc:h2:mem:TicketPilot
    username: sa
    password: password

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false

# Configuration pour Swagger
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    enabled: true